name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Путь к файлу решения, относительно корня проекта
  SOLUTION_FILE_PATH: src/everything.sln  # Укажите путь к вашему .sln файлу
  # Конфигурация сборки (Release или Debug)
  BUILD_CONFIGURATION: Release
  # Платформа (32-битная)
  PLATFORM: x86

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.PLATFORM}} ${{env.SOLUTION_FILE_PATH}}
